// <auto-generated />
namespace AnagramSolver.EFCF.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserLogColumnsOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserLogColumnsOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201802150807183_UserLogColumnsOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
