//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class CachedAnagram
    {
        public int Id { get; set; }
        public int WordId { get; set; }
        public string Anagram { get; set; }
    
        public virtual CachedWord CachedWord { get; set; }
    }
}
