//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserId { get; set; }
        public string UserIp { get; set; }
        public Nullable<int> CachedWordId { get; set; }
        public Nullable<int> WordId { get; set; }
        public Nullable<int> SearchTime { get; set; }
    
        public virtual CachedWord CachedWord { get; set; }
        public virtual Word Word { get; set; }
    }
}
